### ISSUE TITLE
Format of CSV file

### ISSUE THREAD

**Issue by davidyoung8906** [uds-se/mudflow-statistical-analysis#2]
I noticed that in data (https://github.com/uds-se/mudflow-statistical-analysis/tree/master/data) folder, there are three different RDS files. Can you let me know the format of CSV files to generate the RDS files? 
For the initial try, I followed the format of the file on your website (https://www.st.cs.uni-saarland.de/appmining/mudflow/data/data_dump.xlsx) and it does not seems to work. I directly replaced the mudflow_paper.rds with the generated RDS file.  Is there any additional configuration that I should do?

Thanks!

**Comment by davidyoung8906** [comment]
Can any one help to respond?
Thanks!

**Comment by vitaliiavdiienko** [comment]
`file=readRDS("your_rds_file.rds")`
`names(file)`

Enjoy :)

**Comment by davidyoung8906** [comment]
Hi! Vitalii,
      MUDFLOW did know where to find my RDS file because I directly replace the mudflow_paper.rds. What I am asking is the format of the CSV file. Because in your sample file (data_dump.xlsx), data of the benign apps are in a separate spreadsheet from the malware's data, I don't know how to represent the benign or malicious in the CSV/RDS file. Can you provide some hints about this? 

Thanks!
